// <auto-generated />
using System;
using AuctionApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionApp.Migrations.auction
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuctionApp.Persistence.AuctionDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("OpeningBid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18357f3f-feb9-4a21-903b-fb8192c969c8"),
                            Description = "New Auction description",
                            ExpirationDate = new DateTime(2024, 10, 18, 2, 52, 14, 370, DateTimeKind.Local).AddTicks(1784),
                            Name = "New Auction",
                            OpeningBid = 1m,
                            User = "seed@kth.se"
                        });
                });

            modelBuilder.Entity("AuctionApp.Persistence.BidDb", b =>
                {
                    b.Property<Guid>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("BidId");

                    b.HasIndex("AuctionId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            BidId = new Guid("0598c2bf-5add-43bd-a506-2004cb697240"),
                            AuctionId = new Guid("18357f3f-feb9-4a21-903b-fb8192c969c8"),
                            BidAmount = 1m,
                            BidDate = new DateTime(2024, 10, 11, 2, 52, 14, 370, DateTimeKind.Local).AddTicks(2099),
                            User = "bidder@kth.se"
                        },
                        new
                        {
                            BidId = new Guid("da00fe98-e4f4-49d1-a5f2-12eeb2b8d753"),
                            AuctionId = new Guid("18357f3f-feb9-4a21-903b-fb8192c969c8"),
                            BidAmount = 3m,
                            BidDate = new DateTime(2024, 10, 11, 2, 52, 14, 370, DateTimeKind.Local).AddTicks(2104),
                            User = "bidder@kth.se"
                        });
                });

            modelBuilder.Entity("AuctionApp.Persistence.BidDb", b =>
                {
                    b.HasOne("AuctionApp.Persistence.AuctionDb", "AuctionDb")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionDb");
                });

            modelBuilder.Entity("AuctionApp.Persistence.AuctionDb", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
